kick-time: 240 # 4 Hours
kick-message: "You have exceeded your allotted 4 hours on this server today. Try again tomorrow."
kick-broadcast: "{player} has exceeded their allotted 4 hours on this server today."
kick-ignore-users: ["00000000-0000-0000-0000-000000000000"] # Get this from an actual user
timezone: "Etc/UTC"